# Generated by yggtools — do not remove this line.

.PHONY: check test format lint typecheck metrics security build clean

clean:
	mkdir -p work
	find work -mindepth 1 ! -name .gitkeep -exec rm -rf {} +

format:
	uv run ruff format src tests

check: clean
	PYTHONPATH=src uv run python -m yggtools.cli pipeline

test: clean
	uv run pytest

lint: clean
	uv run ruff check src tests

typecheck: clean
	uv run mypy src tests

metrics: clean
	PYTHONPATH=src uv run python -m yggtools.cli run metrics

security: clean
	PYTHONPATH=src uv run python -m yggtools.cli run security-code
	PYTHONPATH=src uv run python -m yggtools.cli run security-deps

build: clean
	uv build --out-dir dist/

ci: clean
	PYTHONPATH=src uv run python -m yggtools.cli pipeline
