"""Quality check: cyclomatic complexity and module line counts."""

from __future__ import annotations

import ast
import fnmatch
import hashlib
import json
import tomllib
from dataclasses import dataclass
from pathlib import Path

from yggtools.quality.runner import CheckResult, register


@dataclass(frozen=True)
class _MetricsConfig:
    """Thresholds from ``[tool.yggtools.code_metrics]`` in pyproject.toml.

    Attributes:
        paths: Directories to inspect.
        exclude: Glob patterns to skip.
        max_cyclomatic_complexity: Maximum allowed complexity per block.
        max_module_logical_lines: Maximum allowed logical lines per module.
    """

    paths: tuple[Path, ...]
    exclude: tuple[str, ...]
    max_cyclomatic_complexity: int
    max_module_logical_lines: int


@dataclass(frozen=True)
class _Violation:
    """A single metrics violation.

    Attributes:
        path: File containing the violation.
        message: Human-readable description.
    """

    path: Path
    message: str


@dataclass(frozen=True)
class _FileChecksum:
    """Checksum information for a file covered by metrics.

    Attributes:
        path: File path relative to the project root.
        sha256: SHA-256 digest of the file content.
        size_bytes: File size in bytes.
    """

    path: str
    sha256: str
    size_bytes: int


def _read_metrics_section(pyproject: Path) -> dict[str, object]:
    """Read the ``[tool.yggtools.code_metrics]`` section from pyproject.toml.

    Args:
        pyproject: Path to the pyproject.toml file.

    Returns:
        The code_metrics dict, or an empty dict if absent or malformed.
    """
    if not pyproject.exists():
        return {}
    with pyproject.open("rb") as fh:
        data = tomllib.load(fh)
    raw = data.get("tool", {})
    if not isinstance(raw, dict):
        return {}
    ygg = raw.get("yggtools", {})
    if not isinstance(ygg, dict):
        return {}
    cm = ygg.get("code_metrics", {})
    return cm if isinstance(cm, dict) else {}


def _load_config(project_dir: Path) -> _MetricsConfig:
    """Load metrics configuration from pyproject.toml.

    Args:
        project_dir: Project root directory.

    Returns:
        Populated _MetricsConfig with defaults when keys are absent.
    """
    section = _read_metrics_section(project_dir / "pyproject.toml")
    raw_paths = section.get("paths", ["src", "tests"])
    raw_exclude = section.get("exclude", [])
    max_cc = section.get("max_cyclomatic_complexity", 10)
    max_ll = section.get("max_module_logical_lines", 900)
    return _MetricsConfig(
        paths=tuple(
            project_dir / p
            for p in (raw_paths if isinstance(raw_paths, list) else [])
        ),
        exclude=tuple(raw_exclude if isinstance(raw_exclude, list) else []),
        max_cyclomatic_complexity=(
            int(max_cc) if isinstance(max_cc, int) else 10
        ),
        max_module_logical_lines=(
            int(max_ll) if isinstance(max_ll, int) else 900
        ),
    )


def _is_excluded(path: Path, patterns: tuple[str, ...]) -> bool:
    """Return True if path matches any exclusion glob pattern.

    Args:
        path: File path to test.
        patterns: Glob patterns to match against the path string.

    Returns:
        True if the path should be excluded.
    """
    return any(fnmatch.fnmatch(str(path), p) for p in patterns)


def _is_generated_python_artifact(path: Path) -> bool:
    """Return True for Python files generated by local execution."""
    return "__pycache__" in path.parts or path.suffix in {".pyc", ".pyo"}


def _relative_to(path: Path, project_dir: Path) -> str:
    """Return path relative to the project root when possible."""
    try:
        return str(path.relative_to(project_dir))
    except ValueError:
        return str(path)


def _iter_configured_files(cfg: _MetricsConfig) -> list[Path]:
    """Return all files covered by the metrics configuration.

    Args:
        cfg: Metrics configuration with paths and exclusions.

    Returns:
        Sorted list of files under configured paths.
    """
    files: list[Path] = []
    for search_path in cfg.paths:
        if not search_path.exists():
            continue
        candidates = (
            [search_path] if search_path.is_file() else search_path.rglob("*")
        )
        files.extend(
            candidate
            for candidate in candidates
            if candidate.is_file()
            and not _is_generated_python_artifact(candidate)
            and not _is_excluded(
                candidate,
                cfg.exclude,
            )
        )
    return sorted(files)


def _checksum_file(path: Path, project_dir: Path) -> _FileChecksum:
    """Compute SHA-256 traceability data for one file."""
    data = path.read_bytes()
    return _FileChecksum(
        path=_relative_to(path, project_dir),
        sha256=hashlib.sha256(data).hexdigest(),
        size_bytes=len(data),
    )


def _write_checksum_manifest(
    checksums: list[_FileChecksum],
    project_dir: Path,
) -> tuple[Path, Path, str]:
    """Write metrics checksum artifacts.

    Args:
        checksums: Checksum records to serialize.
        project_dir: Project root directory.

    Returns:
        Manifest path, manifest checksum path, and manifest SHA-256 digest.
    """
    artifact_dir = project_dir / "work" / "ci" / "artifacts" / "metrics"
    artifact_dir.mkdir(parents=True, exist_ok=True)
    manifest = artifact_dir / "files-manifest.json"
    manifest_checksum = artifact_dir / "files-manifest.sha256"
    payload = [record.__dict__ for record in checksums]
    content = json.dumps(payload, indent=2, sort_keys=True) + "\n"
    digest = hashlib.sha256(content.encode("utf-8")).hexdigest()
    manifest.write_text(content, encoding="utf-8")
    manifest_checksum.write_text(
        f"{digest}  {manifest.name}\n",
        encoding="utf-8",
    )
    return manifest, manifest_checksum, digest


def _cyclomatic_complexity(node: ast.AST) -> int:
    """Compute cyclomatic complexity of an AST node.

    Counts branch points: ``if``, ``elif``, ``for``, ``while``, ``except``,
    ``with``, ``assert``, boolean operators ``and``/``or``, and ternaries.

    Args:
        node: Root AST node of a function or method.

    Returns:
        Cyclomatic complexity value (minimum 1).
    """
    branch_types = (
        ast.If,
        ast.For,
        ast.While,
        ast.ExceptHandler,
        ast.With,
        ast.Assert,
        ast.comprehension,
    )
    count = 1
    for child in ast.walk(node):
        if isinstance(child, branch_types):
            count += 1
        elif isinstance(child, ast.BoolOp):
            count += len(child.values) - 1
        elif isinstance(child, ast.IfExp):
            count += 1
    return count


def _check_file(path: Path, cfg: _MetricsConfig) -> list[_Violation]:
    """Check a single Python file for metrics violations.

    Args:
        path: Path to the Python source file.
        cfg: Metrics configuration with thresholds.

    Returns:
        List of violations found in the file.
    """
    try:
        source = path.read_text(encoding="utf-8")
        tree = ast.parse(source, filename=str(path))
    except SyntaxError:
        return []

    violations: list[_Violation] = []

    logical_lines = sum(
        1
        for node in ast.walk(tree)
        if isinstance(node, ast.stmt)
        and not isinstance(
            node,
            (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef),
        )
    )
    if logical_lines > cfg.max_module_logical_lines:
        violations.append(
            _Violation(
                path=path,
                message=(
                    f"module has {logical_lines} logical lines "
                    f"(max {cfg.max_module_logical_lines})"
                ),
            ),
        )

    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            cc = _cyclomatic_complexity(node)
            if cc > cfg.max_cyclomatic_complexity:
                violations.append(
                    _Violation(
                        path=path,
                        message=(
                            f"{node.name}() CC={cc} "
                            f"(max {cfg.max_cyclomatic_complexity})"
                        ),
                    ),
                )

    return violations


@register("metrics")
def check_metrics(project_dir: Path) -> CheckResult:
    """Check cyclomatic complexity and module line counts.

    Reads thresholds from ``[tool.yggtools.code_metrics]`` in
    ``pyproject.toml``.  Defaults: CC ≤ 10, logical lines ≤ 900.

    Args:
        project_dir: Root directory of the project under audit.

    Returns:
        CheckResult listing violations or confirming all metrics pass.
    """
    cfg = _load_config(project_dir)
    violations: list[_Violation] = []
    configured_files = _iter_configured_files(cfg)
    checksums = [
        _checksum_file(path, project_dir) for path in configured_files
    ]
    manifest, manifest_checksum, manifest_digest = _write_checksum_manifest(
        checksums,
        project_dir,
    )

    python_files = [path for path in configured_files if path.suffix == ".py"]
    for py_file in python_files:
        violations.extend(_check_file(py_file, cfg))

    metadata: dict[str, object] = {
        "files_checksummed": len(checksums),
        "python_files_analyzed": len(python_files),
        "manifest_sha256": manifest_digest,
        "checksums": [record.__dict__ for record in checksums],
    }
    artifacts = (manifest, manifest_checksum)

    if not violations:
        return CheckResult(
            name="metrics",
            passed=True,
            detail=(
                f"All metrics pass; {len(checksums)} file checksum(s) recorded"
            ),
            metadata=metadata,
            artifacts=artifacts,
        )

    first = violations[0]
    metadata["violations"] = [
        {
            "path": _relative_to(violation.path, project_dir),
            "message": violation.message,
        }
        for violation in violations
    ]
    return CheckResult(
        name="metrics",
        passed=False,
        detail=(
            f"{len(violations)} violation(s) — "
            f"{first.path.name}: {first.message}"
        ),
        metadata=metadata,
        artifacts=artifacts,
    )
