name: Test Python Package

on:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:
    branches:
      - master
      - main
      - develop

jobs:
  test:
    name: Run Tests with uv and pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run pytest -v --html=report.html --self-contained-html

      - name: Upload test report artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report.html


      - name: Run tests with coverage
        run: uv run pytest --cov=yggtools --cov-report=term --cov-report=xml

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
