name: Test Python Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests with uv and pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies with uv
        run: uv sync --no-interaction --dev

      - name: Run tests with pytest
        run: uv run pytest -v
